# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "lab-terraform-state-vmq"
    encrypt      = true
    key          = "terragrunt/dev/network/terraform.tfstate"
    region       = "us-east-1"
    use_lockfile = true
  }
}
